name: erc20indexer
version: 1.0.0
description: ERC-20 indexer
networks:
  #59140 for testnet
  - id: 59144
    rpc_config:
      url: https://linea-mainnet.infura.io/v3/3399a6fc18da4932be3d6a64ede25dd3
    start_block: 0
    contracts:
      - name: ERC721
        address:
          #Linea Bored Ape for mainnet?
          - "0xed13d8f1cf662c9641d45504c9ef1148ce5d61ca"
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "Transfer(address from, address to, uint256 tokenId)"
            requiredEntities:
              - name: "User"
                labels:
                  - "userFrom"
                  - "userTo"
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
