name: erc20indexer
version: 1.0.0
description: ERC-20 indexer
networks:
  - id: 59140
    rpc_config:
      url: https://linea-goerli.infura.io/v3/be2db4ab224d45b3a70ad9c3dd7763e6
      unstable__sync_config:
        initial_block_interval: 500
        backoff_multiplicative: 0.8
        acceleration_additive: 5
        interval_ceiling: 5000
        backoff_millis: 5000
        query_timeout_millis: 20000
    start_block: 0
    contracts:
      - name: ERC721
        address:
          # LUCIA
          - "0xF18CDB167A1979224AF5400c4b13251506157743"
          # insiders
          - "0x6AB1CB569ce474Be98e6bDA68d8CEfAAb67e0729"
          # LiNa
          - "0x3Fae32354a1F47Fef1fDc1856944A0fE26Df2705"
          # bored ape yacht
          - "0xd9A8b96f7c8FEd01d5B3730Fbb28B86BDAa574CA"
          # zonic
          - "0x18b64749666fD9eaa188F1A732D26074dd03dF57"
          # Parimals
          - "0xDff3E7c548857399BFF017F7326977eaedBBE948"
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
