name: erc20indexer
version: 1.0.0
description: ERC-20 indexer
networks:
  #59140 for testnet
  - id: 59144
    rpc_config:
      url: https://linea-mainnet.infura.io/v3/3399a6fc18da4932be3d6a64ede25dd3
      # unstable__sync_config:
      #   initial_block_interval: 500
      #   backoff_multiplicative: 0.8
      #   acceleration_additive: 5
      #   interval_ceiling: 5000
      #   backoff_millis: 5000
      #   query_timeout_millis: 20000
    start_block: 0
    contracts:
      - name: ERC721
        address:
          #Linea Bored Ape for mainnet?
          - "0x56B8b60e9aa4c94286bF7139C8f5CD09903D835d"
          - "0xB62C414ABf83c0107DB84f8dE1c88631C05A8D7B"
          - "0xA9d89db621Ce93102c1E8A7Ae6261023B1258361"
        handler: ./src/EventHandlers.bs.js
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 indexed tokenId)"
            requiredEntities:
              - name: Nftcollection
                labels:
                  - "nftCollectionUpdated"
              - name: Token
                labels:
                  - "existingTransferredToken"
